### ISSUE TITLE
Issue with Spinner animate

### ISSUE THREAD

**Issue by Link2Twenty** [Link2Twenty/pull-to-action#10]
Spinner animation some times falls flat. See gif below

![issue](https://cloud.githubusercontent.com/assets/3534427/8570727/4db5f77e-257a-11e5-9a02-5cf3e8d14426.gif)

**Comment by prateekjadhwani** [comment]
This spinner problem is so weird. If you comment the [Line 343 of pull-to-action.html] (https://github.com/Link2Twenty/pull-to-action/blob/master/pull-to-action.html#L342) and then run the code, you will see that `paper-spinner` actually hides itself some seconds later than the actual opacity changes. 
*I think I will need more time to find more details about this problem.*

**Comment by Link2Twenty** [comment]
#spinnerContainer has the class cooldown sometimes, not sure why taking it away solves the issue though.

refreshSpinner.querySelector('#spinnerContainer').classList.remove("cooldown");
