### ISSUE TITLE
Use Polymer 1.0 gesture events

### ISSUE THREAD

**Issue by myfreeweb** [Link2Twenty/pull-to-action#11]
You should use [the new gesture events](https://www.polymer-project.org/1.0/docs/devguide/events.html#gestures) (down, track, up) – that works with the mouse too. And it probably will work with [Pointer Events](http://www.w3.org/TR/pointerevents/) in the future, like [PEP](https://github.com/jquery/PEP) does.

**Comment by Link2Twenty** [comment]
Would you want it to work with a mouse? Having it as responding to touch only was intentional, I thought it would be the only time pull to action would be intuitive.
