### ISSUE TITLE
Port pull-to-action element code to Polymer 1.0

### ISSUE THREAD

**Issue by prateekjadhwani** [Link2Twenty/pull-to-action#3]
With the release of Polymer 1.0 in the upcoming week, we will need to port to code to 1.0 as well. This will need proper discussions about functionalities, coding practices, file structure, etc. But we can go ahead and prepare for the changes in advance.

**Comment by Link2Twenty** [comment]
Waiting for paper-shadow to be ported to 1 before I start, though can start without it I suppose.

**Comment by prateekjadhwani** [comment]
Fixed in https://github.com/Link2Twenty/pull-to-action/pull/7 Pull request.
